###
PUT http://localhost:8888/api/players/import HTTP/1.1
Content-Type: application/json

[
    "__utmz=229377541.1504164268.1.1.utmccn=(direct)|utmcsr=(direct)|utmcmd=(none)", "PHPSESSID=al1c1t3f3tieii51a390v007f7", "halang=en", "__utma=229377541.159156878.1504164268.1507291359.1507720902.28", "__utmc=229377541", "__utmb=229377541"
]

###
GET http://localhost:8080/api/players HTTP/1.1

###
GET http://localhost:8080/api/players/3 HTTP/1.1

###
PUT http://localhost:8888/api/players/3 HTTP/1.1
Content-Type: application/json

{
    "position": "G",
    "status": "MV",
    "loyalty": 2
}

###
GET http://localhost:8888/api/team/update-values HTTP/1.1

###
GET http://localhost:8888/api/team/best-lines HTTP/1.1
