###
PUT http://localhost:8888/api/players HTTP/1.1
Content-Type: application/json

[
    "__utmz=229377541.1506337435.1.1.utmccn=(direct)|utmcsr=(direct)|utmcmd=(none)",
    "halang=en",
    "PHPSESSID=s9afhq8bumb3k0h5mvqbbge0b4",
    "__utma=229377541.1475077041.1506337435.1507273935.1507287319.6",
    "__utmc=229377541",
    "__utmb=229377541"
]

###
GET http://localhost:8888/api/players?sort=latestData.growthPotential,desc HTTP/1.1
